/**
 * Adaptive re-planning (spec §5.5) — the core differentiator.
 *
 * Principles encoded here:
 *   - Reflow the REMAINING plan, never the past. Completed weeks are immutable.
 *   - Protect the goal date by default; only move it when explicitly requested.
 *   - The mechanic is deterministic: re-run the rules engine over the remaining
 *     runway with adjusted inputs, producing a new plan `version`. Diff old vs
 *     new to populate `adaptations.changes`.
 *   - Large changes (goal/target-pace/volume beyond a threshold) require user
 *     consent; minor reflows can apply silently. The LLM writes the human-facing
 *     summary FROM the diff — it never decides the diff.
 */

import type {
  AdaptationTrigger,
  Phase,
  Plan,
  PlanDiff,
  Session,
  TargetVolume,
  Week,
  WeekVolumeDelta,
} from "../types/domain.js";
import { DEFAULT_CONFIG, type EngineConfig } from "./config.js";
import { generatePlan, resolveVdot, type GeneratePlanInput } from "./generatePlan.js";
import { addDays, diffDays } from "./dates.js";

// ---------------------------------------------------------------------------
// Trigger detection
// ---------------------------------------------------------------------------

const KEY_RUN_INTENTS = new Set(["long", "threshold", "interval"]);

export function isKeySession(session: Session): boolean {
  if (session.prescription.type === "strength") return false;
  if (session.prescription.type === "run") {
    return KEY_RUN_INTENTS.has(session.prescription.intent);
  }
  return session.prescription.type === "ruck";
}

export interface MissCounts {
  key: number;
  total: number;
}

/** Count missed (skipped, or past-due still-scheduled) sessions in a window. */
export function countMisses(
  plan: Plan,
  windowStartIso: string,
  windowEndIso: string,
): MissCounts {
  let key = 0;
  let total = 0;
  for (const week of plan.weeks) {
    for (const s of week.sessions) {
      if (s.prescription.type === "rest") continue;
      if (s.scheduled_date < windowStartIso || s.scheduled_date > windowEndIso) continue;
      const missed =
        s.status === "skipped" ||
        (s.status === "scheduled" && s.scheduled_date < windowEndIso);
      if (!missed) continue;
      total++;
      if (isKeySession(s)) key++;
    }
  }
  return { key, total };
}

/** Repeated hard/failed efforts on sessions that should feel moderate. */
export function countUnderperformance(plan: Plan): number {
  let streak = 0;
  let worst = 0;
  const ordered = plan.weeks
    .flatMap((w) => w.sessions)
    .filter((s) => s.status === "completed" && s.effort_flag)
    .sort((a, b) => a.scheduled_date.localeCompare(b.scheduled_date));
  for (const s of ordered) {
    const tooHard =
      (s.effort_flag === "hard" || s.effort_flag === "failed") &&
      !isHardByDesign(s);
    if (tooHard) {
      streak++;
      worst = Math.max(worst, streak);
    } else {
      streak = 0;
    }
  }
  return worst;
}

function isHardByDesign(s: Session): boolean {
  return (
    s.prescription.type === "run" &&
    (s.prescription.intent === "interval" ||
      s.prescription.intent === "threshold" ||
      s.prescription.intent === "repetition")
  );
}

/**
 * Decide whether the plan should adapt and why. Returns the highest-priority
 * trigger, or null if nothing fires. (Manual fatigue / user request are signaled
 * directly by the caller, not detected here.)
 */
export function detectTrigger(
  plan: Plan,
  asOfIso: string,
  config: EngineConfig = DEFAULT_CONFIG,
): AdaptationTrigger | null {
  const windowStart = addDays(asOfIso, -config.adaptation.missWindowDays);
  const misses = countMisses(plan, windowStart, asOfIso);
  if (
    misses.key >= config.adaptation.missedKeyThreshold ||
    misses.total >= config.adaptation.missedTotalThreshold
  ) {
    return "missed_sessions";
  }
  if (countUnderperformance(plan) >= config.adaptation.underperformanceStreak) {
    return "underperformance";
  }
  return null;
}

// ---------------------------------------------------------------------------
// Reflow
// ---------------------------------------------------------------------------

export interface PlanAdjustments {
  /** add to VDOT (negative = ease goal pace after a layoff/underperformance) */
  vdotDelta?: number;
  /** scale the starting volume for the remaining block (e.g. 0.85 after a layoff) */
  volumeScale?: number;
  /** push the goal date out by N days (default 0 = protect the date) */
  pushGoalDays?: number;
}

export interface ReflowResult {
  plan: Plan;
  diff: PlanDiff;
}

/**
 * Reflow the plan from `fromWeekIndex` onward. Weeks before that index are kept
 * byte-for-byte (immutable history). The tail is regenerated by re-running the
 * engine with adjusted inputs, then spliced back on with continuous indices.
 */
export function reflowPlan(
  plan: Plan,
  originalInput: GeneratePlanInput,
  fromWeekIndex: number,
  trigger: AdaptationTrigger,
  adjustments: PlanAdjustments = {},
  config: EngineConfig = DEFAULT_CONFIG,
): ReflowResult {
  const pastWeeks = plan.weeks.filter((w) => w.week_index < fromWeekIndex);
  const tailStartDate = addDays(plan.start_date, fromWeekIndex * 7);

  // Seed the remaining block's starting volume from where the plan currently is,
  // scaled down if the user has been away / struggling.
  const anchorWeek =
    plan.weeks.find((w) => w.week_index === fromWeekIndex) ??
    plan.weeks[plan.weeks.length - 1];
  const currentVolume = anchorWeek?.target_volume.run_distance ?? originalInput.baseline.current_weekly_run_m;
  const volumeScale = adjustments.volumeScale ?? 1;

  const adjustedGoalDate = applyGoalPush(originalInput, adjustments.pushGoalDays ?? 0);

  const adjustedInput: GeneratePlanInput = {
    ...originalInput,
    planId: plan.id,
    startDate: tailStartDate,
    goal: { ...originalInput.goal, goal_date: adjustedGoalDate },
    baseline: {
      ...originalInput.baseline,
      vdot: resolveVdot(originalInput.baseline) + (adjustments.vdotDelta ?? 0),
      current_weekly_run_m:
        currentVolume != null ? Math.round(currentVolume * volumeScale) : undefined,
    },
  };

  const regenerated = generatePlan(adjustedInput);
  const newVersion = plan.version + 1;

  // Splice + re-index the regenerated tail to continue after the past weeks.
  const tailWeeks: Week[] = regenerated.weeks.map((w, i) =>
    reindexWeek(w, fromWeekIndex + i, plan.id, newVersion),
  );

  const newPlan: Plan = {
    ...plan,
    version: newVersion,
    end_date: tailWeeks.length
      ? tailWeeks[tailWeeks.length - 1]!.sessions.at(-1)?.scheduled_date ?? plan.end_date
      : plan.end_date,
    goal_id: plan.goal_id,
    phase_structure: mergePhaseStructure(pastWeeks, tailWeeks),
    weeks: [...pastWeeks, ...tailWeeks],
  };

  const diff = diffPlans(plan, newPlan, fromWeekIndex, originalInput, adjustedGoalDate, config);
  return { plan: newPlan, diff };
}

function applyGoalPush(input: GeneratePlanInput, pushDays: number): string | null {
  if (!input.goal.goal_date) return null;
  return pushDays > 0 ? addDays(input.goal.goal_date, pushDays) : input.goal.goal_date;
}

function reindexWeek(week: Week, newIndex: number, planId: string, version: number): Week {
  const weekId = `${planId}:v${version}:w${newIndex}`;
  return {
    ...week,
    id: weekId,
    plan_id: planId,
    week_index: newIndex,
    sessions: week.sessions.map((s, i) => ({
      ...s,
      id: `${weekId}:${i}`,
      week_id: weekId,
      plan_id: planId,
    })),
  };
}

function mergePhaseStructure(past: Week[], tail: Week[]) {
  const spans: { phase: Phase; week_count: number }[] = [];
  for (const w of [...past, ...tail]) {
    const last = spans[spans.length - 1];
    if (last && last.phase === w.phase) last.week_count++;
    else spans.push({ phase: w.phase, week_count: 1 });
  }
  return spans;
}

// ---------------------------------------------------------------------------
// Diff
// ---------------------------------------------------------------------------

function diffPlans(
  oldPlan: Plan,
  newPlan: Plan,
  fromWeekIndex: number,
  originalInput: GeneratePlanInput,
  adjustedGoalDate: string | null,
  config: EngineConfig,
): PlanDiff {
  const oldByIndex = new Map(oldPlan.weeks.map((w) => [w.week_index, w]));
  const weeks_changed: WeekVolumeDelta[] = [];
  let maxVolumeFraction = 0;

  for (const nw of newPlan.weeks) {
    if (nw.week_index < fromWeekIndex) continue;
    const ow = oldByIndex.get(nw.week_index);
    if (!ow) {
      weeks_changed.push({
        week_index: nw.week_index,
        before: emptyVolume(),
        after: nw.target_volume,
      });
      maxVolumeFraction = 1;
      continue;
    }
    if (!volumeEqual(ow.target_volume, nw.target_volume)) {
      weeks_changed.push({
        week_index: nw.week_index,
        before: ow.target_volume,
        after: nw.target_volume,
      });
      maxVolumeFraction = Math.max(
        maxVolumeFraction,
        volumeFractionDelta(ow.target_volume, nw.target_volume),
      );
    }
  }

  const goalBefore = originalInput.goal.goal_date;
  const goalChanged = goalBefore !== adjustedGoalDate;

  const vdotBefore = resolveVdot(originalInput.baseline);
  const vdotAfter = vdotBefore; // engine doesn't change VDOT; adjustments are explicit
  const requires_consent =
    goalChanged ||
    maxVolumeFraction > config.adaptation.consentVolumeThreshold;

  return {
    goal_date_changed: goalChanged,
    goal_date_before: goalBefore,
    goal_date_after: adjustedGoalDate,
    vdot_before: vdotBefore,
    vdot_after: vdotAfter,
    phase_structure_before: oldPlan.phase_structure,
    phase_structure_after: newPlan.phase_structure,
    weeks_changed,
    requires_consent,
  };
}

function emptyVolume(): TargetVolume {
  return { run_distance: 0, run_time: 0, strength_sessions: 0, ruck_distance: 0 };
}

function volumeEqual(a: TargetVolume, b: TargetVolume): boolean {
  return (
    a.run_distance === b.run_distance &&
    a.run_time === b.run_time &&
    a.strength_sessions === b.strength_sessions &&
    a.ruck_distance === b.ruck_distance
  );
}

function volumeFractionDelta(a: TargetVolume, b: TargetVolume): number {
  const base = Math.max(1, a.run_distance);
  return Math.abs(b.run_distance - a.run_distance) / base;
}
